CREATE DATABASE IF NOT EXISTS crypto_raw;
USE crypto_raw;

CREATE TABLE IF NOT EXISTS raw_coin_list_snapshot (
    raw_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL,
    dag_run_id VARCHAR(128) NULL,
    task_run_id VARCHAR(128) NULL,
    logical_run_ts_utc DATETIME(6) NOT NULL,
    extracted_at_utc DATETIME(6) NOT NULL,
    source_endpoint VARCHAR(255) NOT NULL,
    request_params_json JSON NULL,
    raw_payload_json JSON NOT NULL,
    coin_id VARCHAR(128) NOT NULL,
    symbol VARCHAR(64) NULL,
    coin_name VARCHAR(255) NULL,
    platform_json JSON NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_rcls_coin_id (coin_id),
    KEY idx_rcls_logical_run (logical_run_ts_utc),
    KEY idx_rcls_batch (batch_id)
);

CREATE TABLE IF NOT EXISTS raw_coin_markets_snapshot (
    raw_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL,
    dag_run_id VARCHAR(128) NULL,
    task_run_id VARCHAR(128) NULL,
    logical_run_ts_utc DATETIME(6) NOT NULL,
    extracted_at_utc DATETIME(6) NOT NULL,
    snapshot_ts_utc DATETIME(6) NOT NULL,
    source_endpoint VARCHAR(255) NOT NULL,
    request_params_json JSON NULL,
    raw_payload_json JSON NOT NULL,
    vs_currency VARCHAR(16) NOT NULL,
    page_no INT NOT NULL,
    coin_id VARCHAR(128) NOT NULL,
    symbol VARCHAR(64) NULL,
    coin_name VARCHAR(255) NULL,
    current_price DECIMAL(38,10) NULL,
    market_cap DECIMAL(38,10) NULL,
    market_cap_rank INT NULL,
    total_volume DECIMAL(38,10) NULL,
    high_24h DECIMAL(38,10) NULL,
    low_24h DECIMAL(38,10) NULL,
    price_change_24h DECIMAL(38,10) NULL,
    price_change_percentage_24h DECIMAL(20,10) NULL,
    circulating_supply DECIMAL(38,10) NULL,
    total_supply DECIMAL(38,10) NULL,
    max_supply DECIMAL(38,10) NULL,
    ath DECIMAL(38,10) NULL,
    atl DECIMAL(38,10) NULL,
    last_updated_utc DATETIME(6) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_rcms_snapshot (snapshot_ts_utc),
    KEY idx_rcms_coin_id (coin_id),
    KEY idx_rcms_rank (market_cap_rank),
    KEY idx_rcms_batch (batch_id)
);

CREATE TABLE IF NOT EXISTS raw_coin_market_chart_point (
    raw_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL,
    dag_run_id VARCHAR(128) NULL,
    task_run_id VARCHAR(128) NULL,
    logical_run_ts_utc DATETIME(6) NOT NULL,
    extracted_at_utc DATETIME(6) NOT NULL,
    source_endpoint VARCHAR(255) NOT NULL,
    request_params_json JSON NULL,
    raw_payload_json JSON NOT NULL,
    coin_id VARCHAR(128) NOT NULL,
    vs_currency VARCHAR(16) NOT NULL,
    price_ts_utc DATETIME(6) NOT NULL,
    price_value DECIMAL(38,10) NULL,
    market_cap_value DECIMAL(38,10) NULL,
    total_volume_value DECIMAL(38,10) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_rcmcp_coin_ts (coin_id, price_ts_utc),
    KEY idx_rcmcp_batch (batch_id)
);

CREATE TABLE IF NOT EXISTS raw_global_snapshot (
    raw_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    batch_id VARCHAR(64) NOT NULL,
    dag_run_id VARCHAR(128) NULL,
    task_run_id VARCHAR(128) NULL,
    logical_run_ts_utc DATETIME(6) NOT NULL,
    extracted_at_utc DATETIME(6) NOT NULL,
    snapshot_ts_utc DATETIME(6) NOT NULL,
    source_endpoint VARCHAR(255) NOT NULL,
    request_params_json JSON NULL,
    raw_payload_json JSON NOT NULL,
    active_cryptocurrencies INT NULL,
    upcoming_icos INT NULL,
    ongoing_icos INT NULL,
    ended_icos INT NULL,
    markets INT NULL,
    total_market_cap_usd DECIMAL(38,10) NULL,
    total_volume_usd DECIMAL(38,10) NULL,
    market_cap_percentage_btc DECIMAL(20,10) NULL,
    market_cap_percentage_eth DECIMAL(20,10) NULL,
    market_cap_change_percentage_24h_usd DECIMAL(20,10) NULL,
    updated_at_epoch BIGINT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY idx_rgs_snapshot (snapshot_ts_utc),
    KEY idx_rgs_batch (batch_id)
);